name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ubuntu
      SERVER_KEY: ${{ secrets.SERVER_KEY }}

    steps:
      - uses: actions/checkout@v2

      # 프론트엔드
      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy frontend
        run: |
          echo "$SERVER_KEY" > private_key
          chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "
            cd ~/HandsMarket/frontend &&
            git pull &&
            npm install &&
            npm run build &&
            pm2 restart frontend-app || pm2 start frontend-app --name frontend-app -- serve -s build -l 3000
          "

          rm private_key

      # 백엔드
      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install

      - name: Deploy backend
        run: |
          echo "$SERVER_KEY" > private_key
          chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "
            cd ~/HandsMarket/backend &&
            git pull &&
            npm install &&
            pm2 restart backend-app || pm2 start backend-app --name backend-app -- node ./bin/www
          "

          rm private_key
